use std::fmt::Write as _;
use std::path::Path;

/// 需要生成 gRPC 客户端 + 方法表的 proto。两件事读同一份清单，避免出现
/// 「生成了 stub 但 bridge 不认这个服务」这种半截状态。
///
/// 这几份是从上游手工裁剪的子集 —— **裁掉了什么、为什么，见
/// `proto/README.md`**。没 vendor 的 RPC 在 fresh-box 里根本不存在，所以那份
/// 文档就是「daemon 有这个能力但我们没接」和「daemon 没这个能力」之间唯一的
/// 区分。
const PROTOS: &[&str] = &[
    "proto/daemon/managed_service.proto",
    "proto/daemon/started_service.proto",
    "proto/boxdd/desktop_service.proto",
];

/// 前端可以通过 bridge 调用的方法 —— **只有**这些。
///
/// # 为什么是白名单而不是黑名单
///
/// 这张表以前的极性是反的：方法表由 `PROTOS` 全量生成，再减掉一条
/// `NOT_EXPOSED`。那等价于「vendor 进来什么就暴露什么」，而问题不在某一刻
/// 的宽窄，在**漂移方向**：升 sing-box 版本时要重新 vendor 一份 proto，那次
/// 提交的 diff 是一份 `.proto` 的 diff —— 没有任何一行会告诉 reviewer，它顺带
/// 把上游的 Taildrop 文件收发、Tailscale SSH 会话、USB/IP 之类一并开给了
/// 渲染层。扩大权限是隐式发生、且不可 review 的。
///
/// 反过来之后，扩权必须是这张表上显式的一行，和它对应的前端调用点在同一个
/// PR 里。
///
/// # 这不违反「Rust 一行不用动」
///
/// bridge 的立身之本是字节透传：上游**改字段**时 Rust 一行不用动 —— 这条
/// 完全不受影响，下面列的是方法名，一个字段都不认识。而上游**加 RPC** 时
/// 本来就要先 vendor 进 `proto/` 才存在，那已经是一次 Rust 目录里的编辑；
/// 增量成本只是在同目录的这张表里加一行。
///
/// # 加一条之前
///
/// 问一句这个能力该不该由 webview 直接发起。反例就是 `DesktopService`：它
/// 一条都不在下面，不是因为没人用，而是因为它那些能力（销毁工作目录、接管
/// daemon、导出/删除报告）在 host 域各有一个带守卫、带人话错误的入口，
/// 前端走那条。`StartService` 更是一条安全线 —— 它是唯一能让调用方任意
/// **指定配置内容**的 RPC，开给 webview 等于交出「任意出站、任意 TUN、
/// 任意流量拦截」；启动走 host 域的 `start_singbox(profile_id)`，由 Rust
/// 自己读盘、合成、校验后再调，前端只能说「用哪份配置」。
///
/// 没列进来的方法仍然会进方法表（`exposed: false`），这样 bridge 能把
/// 「故意不暴露」和「根本没这个方法」区分开，报错时一看就知道是哪种。
const EXPOSED: &[(&str, &str)] = &[
    // ── 代理页：组、节点、模式、测速 ──────────────────────────────
    ("daemon.StartedService", "SubscribeGroups"),
    ("daemon.StartedService", "SubscribeClashMode"),
    ("daemon.StartedService", "GetClashModeStatus"),
    ("daemon.StartedService", "SetClashMode"),
    ("daemon.StartedService", "SelectOutbound"),
    ("daemon.StartedService", "URLTest"),
    // ── 总览 / 连接 / 日志 ────────────────────────────────────────
    ("daemon.StartedService", "SubscribeStatus"),
    ("daemon.StartedService", "SubscribeConnections"),
    ("daemon.StartedService", "CloseConnection"),
    ("daemon.StartedService", "CloseAllConnections"),
    ("daemon.StartedService", "SubscribeLog"),
    // ── 诊断页的连通性测试 ────────────────────────────────────────
    ("daemon.StartedService", "StartNetworkQualityTest"),
    ("daemon.StartedService", "StartSTUNTest"),
    // 上面两条要求实例在跑；下面两条住在 worker 自己的管道上，服务没装、
    // 实例没跑照样能用（见 `commands::bridge::channel_for`）。
    (
        "desktop.ApplicationService",
        "StartStandaloneNetworkQualityTest",
    ),
    ("desktop.ApplicationService", "StartStandaloneSTUNTest"),
];

fn main() {
    // SAFETY: build.rs 在任何其他代码之前单线程运行，改进程环境不与任何东西竞争。
    unsafe {
        std::env::set_var("PROTOC", protoc_bin_vendored::protoc_bin_path().unwrap());
    }

    // 生成 sing-box-daemon.exe（boxdd）的 gRPC 客户端 stub。Rust 自己的常驻
    // 逻辑（托盘、reconciliation loop）用这些类型解码；bridge 不用，它走
    // `daemon::bridge::codec::BytesCodec` 字节透传。
    tonic_prost_build::configure()
        .build_server(false)
        .compile_protos(PROTOS, &["proto"])
        .expect("failed to compile sing-box-daemon gRPC protos");

    generate_method_table();

    tauri_build::build();
}

#[derive(Debug)]
struct Method {
    service: String,
    name: String,
    server_streaming: bool,
}

/// 从 `PROTOS` 里扫出全部 `rpc`，生成 `daemon::bridge::allowlist` include 的
/// 静态方法表。
///
/// 这张表就是 bridge 的能力边界：只有 `exposed: true` 的 service/method 才能
/// 被前端调到，而那一列直接来自 `EXPOSED`（见它的文档注释）。表里同时保留
/// 未暴露的方法，是为了让 bridge 能区分「故意不给」和「压根没有」。
///
/// 用的是逐行扫描而不是完整的 proto 解析器：这几份 proto 是手工裁剪、格式
/// 统一的（`rpc Name(Req) returns (stream Resp) {}` 一行一条），引一个解析器
/// 依赖不划算。格式一旦不符，下面的断言会让构建直接失败，而不是静默漏掉方法。
fn generate_method_table() {
    let mut methods = Vec::new();
    for proto in PROTOS {
        println!("cargo:rerun-if-changed={proto}");
        methods.extend(parse_proto(Path::new(proto)));
    }

    assert!(
        !methods.is_empty(),
        "no rpc methods parsed from {PROTOS:?} — proto layout changed?"
    );

    // EXPOSED 里写错服务名/方法名的后果是「以为开了，其实没开」—— 表现为
    // 运行期一句 PermissionDenied，而不是构建失败。所以在这里核对：列进去
    // 的必须真实存在。上游重命名一个 RPC 时，这条断言也是第一个报警的地方。
    for (service, name) in EXPOSED {
        assert!(
            methods
                .iter()
                .any(|m| m.service == *service && m.name == *name),
            "EXPOSED entry {service}/{name} does not match any rpc in {PROTOS:?}"
        );
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("pub static METHODS: &[MethodEntry] = &[\n");
    for method in &methods {
        let exposed = EXPOSED
            .iter()
            .any(|(s, n)| *s == method.service && *n == method.name);
        writeln!(
            out,
            "    MethodEntry {{ service: {:?}, method: {:?}, path: {:?}, server_streaming: {}, exposed: {} }},",
            method.service,
            method.name,
            format!("/{}/{}", method.service, method.name),
            method.server_streaming,
            exposed,
        )
        .expect("writing to a String cannot fail");
    }
    out.push_str("];\n");

    let dest =
        Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is always set for build scripts"))
            .join("daemon_methods.rs");
    std::fs::write(&dest, out).expect("failed to write generated daemon method table");
}

fn parse_proto(path: &Path) -> Vec<Method> {
    let source = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));

    let mut package = String::new();
    let mut service: Option<String> = None;
    let mut methods = Vec::new();

    for raw_line in source.lines() {
        // 只需要去掉整行注释：这些 proto 里没有行尾 `//`，而 `rpc` 行里也
        // 不会出现 `//`，所以不必做完整的注释剥离。
        let line = raw_line.trim();
        if line.starts_with("//") {
            continue;
        }

        if let Some(rest) = line.strip_prefix("package ") {
            package = rest.trim_end_matches(';').trim().to_string();
            continue;
        }

        if let Some(rest) = line.strip_prefix("service ") {
            let name = rest.split_whitespace().next().unwrap_or_default();
            assert!(
                !package.is_empty(),
                "{}: `service {name}` appears before `package`",
                path.display()
            );
            service = Some(format!("{package}.{name}"));
            continue;
        }

        if line == "}" {
            service = None;
            continue;
        }

        let Some(service) = service.as_deref() else {
            continue;
        };
        let Some(rest) = line.strip_prefix("rpc ") else {
            continue;
        };

        let (name, after_name) = rest
            .split_once('(')
            .unwrap_or_else(|| panic!("{}: malformed rpc line: {line}", path.display()));
        let returns = after_name
            .split_once("returns")
            .unwrap_or_else(|| panic!("{}: rpc without `returns`: {line}", path.display()))
            .1
            .trim_start()
            .strip_prefix('(')
            .unwrap_or_else(|| panic!("{}: malformed rpc return type: {line}", path.display()));

        methods.push(Method {
            service: service.to_string(),
            name: name.trim().to_string(),
            // 客户端流（`rpc F(stream Req)`）boxdd 一个都没有，所以这里只区分
            // 一元和服务端流两种。真出现了，下面的断言会挡住。
            server_streaming: returns.trim_start().starts_with("stream "),
        });

        assert!(
            !after_name.trim_start().starts_with("stream "),
            "{}: client-streaming rpc is not supported by the bridge: {line}",
            path.display()
        );
    }

    methods
}
