use std::fmt::Write as _;
use std::path::Path;

/// 需要生成 gRPC 客户端 + 方法表的 proto。两件事读同一份清单，避免出现
/// 「生成了 stub 但 bridge 不认这个服务」这种半截状态。
const PROTOS: &[&str] = &[
    "proto/daemon/managed_service.proto",
    "proto/daemon/started_service.proto",
    "proto/boxdd/desktop_service.proto",
];

/// 明确**不**通过 bridge 暴露给前端的方法。
///
/// 这是一条安全线，不是实现细节：`StartService` 是唯一一个能让调用方任意
/// 指定 sing-box 配置内容的 RPC，把它开放给 webview 等于交出「任意出站、
/// 任意 TUN、任意流量拦截」。启动走 host 域的 `host_start_profile(id)`，
/// 由 Rust 自己读盘、合成、校验后再调 —— 前端只能说「用哪份配置」，不能
/// 说「用这些内容」。
///
/// 这里列出的方法仍然会进方法表（`exposed: false`），这样 bridge 能把
/// 「故意不暴露」和「根本没这个方法」区分开，报错时前端一看就知道是哪种。
const NOT_EXPOSED: &[(&str, &str)] = &[("desktop.DesktopService", "StartService")];

fn main() {
    // SAFETY: build.rs 在任何其他代码之前单线程运行，改进程环境不与任何东西竞争。
    unsafe {
        std::env::set_var("PROTOC", protoc_bin_vendored::protoc_bin_path().unwrap());
    }

    // 生成 sing-box-daemon.exe（boxdd）的 gRPC 客户端 stub。Rust 自己的常驻
    // 逻辑（托盘、reconciliation loop）用这些类型解码；bridge 不用，它走
    // `daemon::bridge::codec::BytesCodec` 字节透传。
    tonic_prost_build::configure()
        .build_server(false)
        .compile_protos(PROTOS, &["proto"])
        .expect("failed to compile sing-box-daemon gRPC protos");

    generate_method_table();

    tauri_build::build();
}

#[derive(Debug)]
struct Method {
    service: String,
    name: String,
    server_streaming: bool,
}

/// 从 `PROTOS` 里扫出全部 `rpc`，生成 `daemon::bridge::allowlist` include 的
/// 静态方法表。
///
/// 这张表就是 bridge 的能力边界：只有表里 `exposed: true` 的 service/method
/// 才能被前端调到。于是「vendored proto 只裁剪到用得着的子集」这件原本像
/// 技术债的事，变成了一份显式的能力清单 —— 想加一个 daemon 能力，必须先动
/// `.proto`，天然过一次 review。
///
/// 用的是逐行扫描而不是完整的 proto 解析器：这几份 proto 是手工裁剪、格式
/// 统一的（`rpc Name(Req) returns (stream Resp) {}` 一行一条），引一个解析器
/// 依赖不划算。格式一旦不符，下面的断言会让构建直接失败，而不是静默漏掉方法。
fn generate_method_table() {
    let mut methods = Vec::new();
    for proto in PROTOS {
        println!("cargo:rerun-if-changed={proto}");
        methods.extend(parse_proto(Path::new(proto)));
    }

    assert!(
        !methods.is_empty(),
        "no rpc methods parsed from {PROTOS:?} — proto layout changed?"
    );

    // NOT_EXPOSED 里写错服务名/方法名会让安全意图静默失效（以为挡住了，其实
    // 没挡），所以在这里核对一遍：列进去的必须真实存在。
    for (service, name) in NOT_EXPOSED {
        assert!(
            methods
                .iter()
                .any(|m| m.service == *service && m.name == *name),
            "NOT_EXPOSED entry {service}/{name} does not match any rpc in {PROTOS:?}"
        );
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("pub static METHODS: &[MethodEntry] = &[\n");
    for method in &methods {
        let exposed = !NOT_EXPOSED
            .iter()
            .any(|(s, n)| *s == method.service && *n == method.name);
        writeln!(
            out,
            "    MethodEntry {{ service: {:?}, method: {:?}, path: {:?}, server_streaming: {}, exposed: {} }},",
            method.service,
            method.name,
            format!("/{}/{}", method.service, method.name),
            method.server_streaming,
            exposed,
        )
        .expect("writing to a String cannot fail");
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is always set for build scripts"))
        .join("daemon_methods.rs");
    std::fs::write(&dest, out).expect("failed to write generated daemon method table");
}

fn parse_proto(path: &Path) -> Vec<Method> {
    let source = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));

    let mut package = String::new();
    let mut service: Option<String> = None;
    let mut methods = Vec::new();

    for raw_line in source.lines() {
        // 只需要去掉整行注释：这些 proto 里没有行尾 `//`，而 `rpc` 行里也
        // 不会出现 `//`，所以不必做完整的注释剥离。
        let line = raw_line.trim();
        if line.starts_with("//") {
            continue;
        }

        if let Some(rest) = line.strip_prefix("package ") {
            package = rest.trim_end_matches(';').trim().to_string();
            continue;
        }

        if let Some(rest) = line.strip_prefix("service ") {
            let name = rest.split_whitespace().next().unwrap_or_default();
            assert!(
                !package.is_empty(),
                "{}: `service {name}` appears before `package`",
                path.display()
            );
            service = Some(format!("{package}.{name}"));
            continue;
        }

        if line == "}" {
            service = None;
            continue;
        }

        let Some(service) = service.as_deref() else {
            continue;
        };
        let Some(rest) = line.strip_prefix("rpc ") else {
            continue;
        };

        let (name, after_name) = rest
            .split_once('(')
            .unwrap_or_else(|| panic!("{}: malformed rpc line: {line}", path.display()));
        let returns = after_name
            .split_once("returns")
            .unwrap_or_else(|| panic!("{}: rpc without `returns`: {line}", path.display()))
            .1
            .trim_start()
            .strip_prefix('(')
            .unwrap_or_else(|| panic!("{}: malformed rpc return type: {line}", path.display()));

        methods.push(Method {
            service: service.to_string(),
            name: name.trim().to_string(),
            // 客户端流（`rpc F(stream Req)`）boxdd 一个都没有，所以这里只区分
            // 一元和服务端流两种。真出现了，下面的断言会挡住。
            server_streaming: returns.trim_start().starts_with("stream "),
        });

        assert!(
            !after_name.trim_start().starts_with("stream "),
            "{}: client-streaming rpc is not supported by the bridge: {line}",
            path.display()
        );
    }

    methods
}
